// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagementApi;

#nullable disable

namespace ProductManagementApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class ProductManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductManagementApi.Product.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Smartphone",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Smartwatch",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wireless Earbuds",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Digital Camera",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 6,
                            Name = "4K TV",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gaming Console",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fitness Tracker",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Tablet",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Headphones",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Smart Home Hub",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Robot Vacuum",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Coffee Maker",
                            Price = 69.99m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bluetooth Speaker",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Wireless Charger",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Drone",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 17,
                            Name = "E-book Reader",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 18,
                            Name = "Portable Power Bank",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 19,
                            Name = "External Hard Drive",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 20,
                            Name = "Action Camera",
                            Price = 149.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
